// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuY-rXsrKEoVLtxyy8OL_mJKlG1ayp_t0',
    appId: '1:993134944260:web:71bf13cd1a2b877ac2d551',
    messagingSenderId: '993134944260',
    projectId: 'spotify12121abu',
    authDomain: 'spotify12121abu.firebaseapp.com',
    storageBucket: 'spotify12121abu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSdVk1auRhuGhwO_45VKp7KwUOfk9mkT8',
    appId: '1:993134944260:android:a0eb33b7abe40640c2d551',
    messagingSenderId: '993134944260',
    projectId: 'spotify12121abu',
    storageBucket: 'spotify12121abu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4uUNXk4-EEb8rRW4EyE3rL2c4a4fy2q8',
    appId: '1:993134944260:ios:0ee386468bf7b78ac2d551',
    messagingSenderId: '993134944260',
    projectId: 'spotify12121abu',
    storageBucket: 'spotify12121abu.appspot.com',
    iosBundleId: 'com.example.spotifyclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4uUNXk4-EEb8rRW4EyE3rL2c4a4fy2q8',
    appId: '1:993134944260:ios:0ee386468bf7b78ac2d551',
    messagingSenderId: '993134944260',
    projectId: 'spotify12121abu',
    storageBucket: 'spotify12121abu.appspot.com',
    iosBundleId: 'com.example.spotifyclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuY-rXsrKEoVLtxyy8OL_mJKlG1ayp_t0',
    appId: '1:993134944260:web:e4c3adf7b448fdc6c2d551',
    messagingSenderId: '993134944260',
    projectId: 'spotify12121abu',
    authDomain: 'spotify12121abu.firebaseapp.com',
    storageBucket: 'spotify12121abu.appspot.com',
  );
}
